### ISSUE TITLE
com.sun.opengl.*

### ISSUE THREAD

**Issue by knupel** [memoakten/p5-MSAFluid#3]
Hello Memo,

I try to work with MSFluid with P212 and Java 7.55 on OSX 10.9.2, but there is problem.
I receive this error : 
No library found for com.sun.opengl.util
Libraries must be installed in a folder named 'libraries' inside the 'sketchbook' folder.

When I import : import com.sun.opengl.*; I receive this error message : 
No library found for com.sun.opengl
No library found for com.sun.opengl.util

When I search information on the web about that I find that : 
http://gamedev.stackexchange.com/questions/46793/cant-import-sun-opengl

Any idea ?

**Comment by ThomasLengeling** [comment]
hey you could try my fork everything is working up to the new version of processing https://github.com/ThomasLengeling/p5-MSAFluid

**Comment by knupel** [comment]
Thx that work very fine.

++
